### ISSUE TITLE
Update of https ssl certificate for www.wmo.int

### ISSUE THREAD

**Issue by fredgalati** [wmo-im/ops#6]
Sent @kurt-hectic by Email for set-up

**Comment by kurt-hectic** [comment]
it seems the certificates are still valid until Feb 2020?

![image](https://user-images.githubusercontent.com/215973/65419997-47f33c00-de00-11e9-95af-e8b5bfa991f4.png)

**Comment by fredgalati** [comment]
You are using here the Wildcard *.wmo.int not the specific for www.wmo.int.
Can you check? Thanks and regards

**Comment by kurt-hectic** [comment]
as you can see we use the * certificate for www.wmo.int . (e.g https://www.wmo.int/pages/prog/www/wigos/index_en.html)

I do not know where certificate you just renewed is supposed to be used.

**Comment by fredgalati** [comment]
Sorry Timo, i checked again and indeed you are using the wildcard of wmo.int,
not the one for www. Domain specific.

I also checked with David L. and he confirmed me the same. Pls replace it
but we may need to re-issue the key as well cause then we were not using
the good one for www.wmo.int. I'll get back. Thanks

**Comment by fredgalati** [comment]
Agreed to wait Feb 2020
